services:
  civic-sense-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nest
    volumes:
      - civic-sense-db:/var/lib/postgresql/data
    networks:
      - civic-sense-network

volumes:
  civic-sense-db:

networks:
    civic-sense-network:
      driver: bridge